name: macOS-latest Qt6 Build

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  ALIAS_BRANCH: macos-latest

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          submodules: recursive

      - name: Move alias branch `macos-latest` to latest commit
        run: |
          git branch -f ${{ env.ALIAS_BRANCH }} master
          git push origin ${{ env.ALIAS_BRANCH }}

      - name: Wait for branch to sync (prevent race condition)
        run: sleep 5
        shell: bash

      - name: Create a temporary tag using commit hash
        shell: bash
        run: |
          SHORT_HASH=$(git rev-parse --short ${{ env.ALIAS_BRANCH }})
          TEMP_TAG="macos-latest-$SHORT_HASH"
          echo "TEMP_TAG=$TEMP_TAG" >> $GITHUB_ENV
          git tag "$TEMP_TAG" ${{ env.ALIAS_BRANCH }}
          git push origin "$TEMP_TAG"

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Qt6 via Homebrew
        run: |
          brew update
          brew install qt@6
          echo "$(brew --prefix qt@6)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix qt@6)/lib" >> $GITHUB_PATH
          echo "$(brew --prefix qt@6)/include" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/ -DCMAKE_PREFIX_PATH=$(brew --prefix qt@6)

      - name: Build
        run: |
          cd build
          cmake --build . -- -j$(sysctl -n hw.ncpu)

      - name: Install
        run: |
          cd build
          cmake --install .

      - name: Rename Executable with Branch Alias
        run: mv /tmp/DaisyChain.dmg /tmp/DaisyChain-macos.dmg
        shell: bash

      - name: Create New GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ env.TEMP_TAG }}
          files: /tmp/DaisyChain-macos.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old `macos-latest-*` tags to prevent clutter
        shell: bash
        run: |
          git fetch --prune --tags
          git tag --list "macos-latest-*" --sort=-creatordate | tail -n +4 | xargs -r git push --delete origin
