name: macOS-12 Qt6 Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-12

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies (Homebrew and Qt6)
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install Qt6 via Homebrew
        run: |
          brew update
          brew install qt@6
          echo "$(brew --prefix qt@6)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix qt@6)/lib" >> $GITHUB_PATH
          echo "$(brew --prefix qt@6)/include" >> $GITHUB_PATH

      # Configure the build (Assuming CMake project)
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/ -DCMAKE_PREFIX_PATH=$(brew --prefix qt@6)

      # Build the project
      - name: Build
        run: |
          cd build
          cmake --build . -- -j$(sysctl -n hw.ncpu)
          
      # Install the project
      - name: Install
        run: |
          cd build
          cmake --install .

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daisychain-macos-12-build
          path: /tmp/DaisyChain.dmg

      # Overwrite 'macos-12-latest' tag
      - name: Delete existing release and tag
        run: |
          release_id=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/macos-12-latest" | jq -r .id)
          
          if [ "$release_id" != "null" ]; then
            echo "Deleting release with id: $release_id"
            curl -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
          
            echo "Deleting tag: macos-12-latest"
            git push origin --delete macos-12-latest
          fi

      # Create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: macos-12-latest
          release_name: Latest Artifacts
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload release
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/DaisyChain.dmg
          asset_name: DaisyChain.dmg
          asset_content_type: application/zip
